name: Docker Image Deploy

on:
  push:
    branches: [ "develop" ]
    tags: [ "v*.*.*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Image
        run: |
          docker build -t peng49/gocron:latest -f Dockerfile.release .

      - name: Deploy Image
        env:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
        run: |
          export appVersion=$(cat cmd/gocron/gocron.go | grep 'AppVersion =' | awk '{print $3}' | sed 's/"//g')
          echo 'GITHUB_REF:' $GITHUB_REF
          docker tag peng49/gocron:latest "${username}/gocron:v${appVersion}"
          docker images
          echo "${password}" | docker login -u "${username}" --password-stdin
          docker push "${username}/gocron:latest"